name: fordev
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  equatable: 
  flutter_secure_storage:
  get: 
  http: 
  provider: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: 
  flutter_launcher_icons: 
  mocktail: 
  test: 

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/

flutter_icons:
  ios: true
  android: true
  image_path_android: assets/icon/android.png
  image_path_ios: assets/icon/ios.png
  adaptive_icon_background: assets/icon/background.png
  adaptive_icon_foreground: assets/icon/foreground.png